raw_data_path: "data/raw/weatherHistory.csv"
processed_data_path: "data/processed/weather_cleaned.csv"

eda:
  interactive: True
  categorical_cols: ['Summary', 'Precip Type', 'Season']
  time_col: 'Formatted Date'
  numerical_cols: ['Temperature (C)', 'Apparent Temperature (C)', 'Humidity', 'Wind Speed (km/h)', 'Visibility (km)', 'Pressure (millibars)']
  eda:
  numerical_cols_small: ['Humidity']
  numerical_cols_medium: ['Temperature (C)', 'Apparent Temperature (C)', 'Wind Speed (km/h)', 'Visibility (km)']
  numerical_cols_large: ['Pressure (millibars)']
  target_col: 'Precip Type'

preprocessing:
  drop_cols: ['Loud Cover', 'Daily Summary']
  temp_bins: [-50, 0, 15, 25, 100]
  temp_labels: ['Freezing', 'Cold', 'Warm', 'Hot']
  humidity_bins: [0, 0.4, 0.7, 1.0]
  humidity_labels: ['Dry', 'Normal', 'Wet']
