raw_data_path: "data/raw/weatherHistory.csv"
processed_data_path: "data/processed/weather_cleaned.csv"

eda:
  interactive: True
  categorical_cols: ['Summary', 'Precip Type', 'Season']
  time_col: 'Formatted Date'
  numerical_cols: ['Temperature (C)', 'Apparent Temperature (C)', 'Humidity', 'Wind Speed (km/h)', 'Visibility (km)', 'Pressure (millibars)']
  eda:
  numerical_cols_small: ['Humidity']
  numerical_cols_medium: ['Temperature (C)', 'Apparent Temperature (C)', 'Wind Speed (km/h)', 'Visibility (km)']
  numerical_cols_large: ['Pressure (millibars)']
  target_col: 'Precip Type'


preprocessing:
  drop_cols: ['Loud Cover', 'Daily Summary']
  # Ngưỡng chia nhiệt độ (C)
  temp_bins: [-50, 0, 15, 25, 100]
  temp_labels: ['Freezing', 'Cold', 'Warm', 'Hot']
  # Ngưỡng chia độ ẩm
  humidity_bins: [0, 0.4, 0.7, 1.1]
  humidity_labels: ['Dry', 'Normal', 'Wet']
  # Ngưỡng chia tầm nhìn (km)
  visibility_bins: [0, 5, 10, 100]
  visibility_labels: ['Low', 'Medium', 'High']

mining:
  min_support: 0.05
  min_threshold_lift: 1.2
  target_seasons: ['Spring', 'Summer', 'Autumn', 'Winter']

clustering:
  features: ['Temperature (C)', 'Humidity', 'Wind Speed (km/h)', 'Pressure (millibars)']
  n_clusters: 4  # Giả định 4 nhóm thời tiết chính
  random_state: 42

outputs:
  mining_dir: "outputs/tables/"
  figures_dir: "outputs/figures/"
  models_dir: "outputs/models/"
  rules_filename: "association_rules_seasonal.csv"

classification:
  target: 'Summary'
  features: ['Temperature (C)', 'Humidity', 'Wind Speed (km/h)', 'Pressure (millibars)', 'Visibility (km)', 'Precip Type', 'Month']
  test_size: 0.2
  random_state: 42
  models:
    rf_params:
      n_estimators: 100
      max_depth: 15
      class_weight: 'balanced' # Quan trọng cho nhãn mất cân bằng
    xgb_params:
      n_estimators: 100
      learning_rate: 0.1
      max_depth: 6

